---
title: "text_analysis"
author: "Tim"
date: "June 27, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


source("./common_fxns.R")
packages <- c("tidytext", "tidyverse")
ipak(packages)
dir_data <- "../data"


```

```{r data}

species_threats_narrative <- read_csv(file.path(dir_data, "species_threats_narrative.csv"))
species_nonfishing_narrative <- read_csv(file.path(dir_data, "species_nonfishing_threats_narrative.csv"))

species_threats_narrative <- bind_rows(species_threats_narrative, species_nonfishing_narrative) %>% 
  dplyr::select(-c(name, result.species_id))

#Attempt text analysis of narrative on threats:
tidy_narrative <- unnest_tokens(species_threats_narrative, word, result.threats)
data(stop_words)
words <- c("em", "species", "br", "al", "shark", "span", "style", "pers", "comm", "lang", "en", "space")
new_stop_words <- tibble(word=words, lexicon=rep("Cashion", times=length(words)))
stop_words <- stop_words %>% bind_rows(new_stop_words)
```

```{r simple-gears}


tidy_narrative <- tidy_narrative %>% anti_join(stop_words)
gears <- c("trawl", "gillnet", "seine", "longline", "hook", "line", "net", "entangle", "netting", "hooking", "hook and", "hook and line", "gill net", "bottom trawl")
tidy_narrative_gears <-  tidy_narrative %>% filter(word %in% gears)

tidy_narrative_gears %>%
  count(word, sort = TRUE) %>%
  #filter(n > 400) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()



```

```{r}

#Attempt text analysis of narrative on threats with n-grams:
tidy_narrative_bigrams <- species_threats_narrative %>% unnest_tokens(bigram, result.threats, token="ngrams", n=2)
tidy_narrative_bigrams_separated <- tidy_narrative_bigrams %>%
  separate(bigram, c("word1", "word2"), sep = " ")

bigrams_filtered <- tidy_narrative_bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

# new bigram counts:
bigram_counts <- bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)

bigrams_united <- bigrams_filtered %>% 
  unite(bigram, word1, word2, sep= " ")


gears <- c("trawl", "gillnet", "seine", "longline", "hook", "line", "net", "entangle", "netting", "hooking", "hook and", "hook and line", "gill net", "bottom trawl")
gears_c <- str_c(gears, collapse="|")
incorrect_matches <- c("decline")
tidy_narrative_gears <-  tidy_narrative %>% filter(word %in% gears) %>% filter(!word %in% incorrect_matches)

bigrams_united %>% 
  filter(grepl(bigram, pattern=gears_c)) %>% 
  filter(!grepl(bigram, pattern=incorrect_matches)) %>% 
  count(bigram, sort = TRUE) %>%
  filter(n > 100) %>%
  mutate(bigram = reorder(bigram, n)) %>%
  ggplot(aes(bigram, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() 


```


```{r clean-narrative-output}
#Clean data by bigrams to determine fishery gear threat by species:
tidy_threat_bigrams <- species_threats_narrative %>% dplyr::select(-result.usetrade) %>% unnest_tokens(bigram, result.threats, token="ngrams", n=2)
tidy_use_bigrams <- species_threats_narrative %>% dplyr::select(-result.threats)  %>% unnest_tokens(bigram, result.usetrade, token="ngrams", n=2)
tidy_bigrams <- bind_rows(tidy_threat_bigrams, tidy_use_bigrams)
data(stop_words)
words <- c("em", "species", "br", "al", "shark", "span", "style", "pers", "comm", "lang", "en", "space", "decline", "declines", "declined","underline", "shoreline", "wrack line", "online")
new_stop_words <- data_frame(word=words, lexicon=rep("Cashion", times=length(words)))
stop_words <- stop_words %>% bind_rows(new_stop_words)

tidy_bigrams_separated <- tidy_bigrams %>%
  separate(bigram, c("word1", "word2"), sep = " ")

bigrams_filtered <- tidy_bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

# new bigram counts:
bigram_counts <- bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)

bigrams_united <- bigrams_filtered %>% 
  unite(bigram, word1, word2, sep= " ")


bottom_trawls <- c("bottom trawl|deepwater trawl|demersal trawl|prawn trawl|benthic trawl|otter trawl|beam trawl|shrimp trawl")
pelagic_trawls <- c("pelagic trawl|shallow trawl|midwater trawl|surface trawl")
trawls <- c("trawl|trawling")
longlines <- c("longline|hooks")
lines <- c("hook and line|hook and|and line|hook|line|pole and|jig|hand line")
nets <- c("net")
seines <- c("seine|purse|encircling")
gillnets <- c("gill net|gillnet|entangl|entangle")
dredges <- c("dredge|drag")
others <- c("harpoon|bagnets|bag|spear|blast|cyanide")
others <- c("harpoon|bagnets|bag|spear")

traps <- c("pot|trap|fyke")
small_scale <- c("small scale|artisanal|subsistence|small-scale")
drifting_longlines <- c("drifting longlines|drifting lines")
squid_jiggers <- c("jig|squid jiggers|jiggers|squid jigging|jigging")


gear_search_table <- tibble(`Gear type` = c("Bottom trawl", "Pelagic trawl", "Trawl", "Longlines", "Lines", "Nets", "Seines", "Gillnets",
                                            "Dredges", "Traps", "Drifting longlines", "Squid jiggers", "Small scale", "Others"),
                             `Search terms` = c(bottom_trawls, pelagic_trawls, trawls, longlines, lines, nets, seines, gillnets, 
                                                dredges, traps, drifting_longlines, squid_jiggers, small_scale, others))
write_csv(gear_search_table, "../output/gear_search_terms_table.csv")

bigrams_united <- bigrams_united %>% 
  mutate(bottom_trawl = NA,
         pelagic_trawl = NA,
         trawl_unspec = NA, 
         longline = NA,
         drifting_longlines = NA,
         squid_jigger = NA,
         line = NA,
         net = NA,
         purse_seine = NA,
         gillnet = NA,
         dredge = NA,
         trap = NA,
         small_scale = NA,
         other = NA
         )

bigrams_united$bottom_trawl[grepl(bigrams_united$bigram, pattern=bottom_trawls)] <- 1
bigrams_united$pelagic_trawl[grepl(bigrams_united$bigram, pattern=pelagic_trawls)] <- 1
bigrams_united$trawl_unspec[grepl(bigrams_united$bigram, pattern=trawls)] <- 1
bigrams_united$longline[grepl(bigrams_united$bigram, pattern=longlines)] <- 1

bigrams_united$line[grepl(bigrams_united$bigram, pattern=lines)] <- 1
bigrams_united$net[grepl(bigrams_united$bigram, pattern=nets)] <- 1
bigrams_united$purse_seine[grepl(bigrams_united$bigram, pattern=seines)] <- 1
bigrams_united$gillnet[grepl(bigrams_united$bigram, pattern=gillnets)] <- 1
bigrams_united$dredge[grepl(bigrams_united$bigram, pattern=dredges)] <- 1
bigrams_united$trap[grepl(bigrams_united$bigram, pattern=traps)] <- 1
bigrams_united$small_scale[grepl(bigrams_united$bigram, pattern=small_scale)] <- 1
bigrams_united$other[grepl(bigrams_united$bigram, pattern=others)] <- 1

#GFW Specifically
bigrams_united$drifting_longlines[grepl(bigrams_united$bigram, pattern=drifting_longlines)] <- 1
bigrams_united$squid_jigger[grepl(bigrams_united$bigram, pattern=squid_jiggers)] <- 1




output <- bigrams_united %>% 
  #rename(scientific_name=name) %>% 
  dplyr::select(-bigram) %>% 
  group_by(iucn_id) %>% 
  summarize_at(vars(bottom_trawl:other), mean, na.rm = TRUE)

write_csv(output, file.path(dir_data, "narrative_threats_output.csv"))
```

```{r}
#Habitat modification
habitat <- c("habitat modification|habitat destruction")
bigrams_united$habitat <- NA
bigrams_united$habitat[grepl(bigrams_united$bigram, pattern=habitat)] <- 1

output <- bigrams_united %>% 
  #rename(scientific_name=name) %>% 
  dplyr::select(-bigram) %>% 
  group_by(iucn_id) %>% 
  summarize_at(vars(bottom_trawl:habitat), mean, na.rm = TRUE)
output

trawl_habitat_modifying <- output %>% filter(habitat==1) %>% filter(bottom_trawl==1|pelagic_trawl==1|trawl_unspec==1)
trawl_habitat_possible <- species_threats_narrative %>% filter(iucn_id %in% trawl_habitat_modifying$iucn_id)

habitat_causal <- c("habitat modification from fish|habitat destruction from fish|habitat destruction from destructive fish|habitat modification from destructive fish|destructive fishing practices")
trawl_habitat_possible$causal <- NA
trawl_habitat_possible$causal[grepl(trawl_habitat_possible$result.threats, pattern=habitat_causal)] <- 1
trawl_habitat_possible$causal[grepl(trawl_habitat_possible$result.usetrade, pattern=habitat_causal)] <- 1
sum(trawl_habitat_possible$causal,na.rm=TRUE)

trawl_habitat_possible$dynamite <- NA
trawl_habitat_possible$dynamite[grepl(trawl_habitat_possible$result.threats, pattern="dynamite|explosiv")] <- 1
trawl_habitat_possible$dynamite[grepl(trawl_habitat_possible$result.usetrade, pattern="dynamite|explosiv")] <- 1
sum(trawl_habitat_possible$dynamite,na.rm=TRUE)

trawl_habitat_possible$destructive <- NA
trawl_habitat_possible$destructive[grepl(trawl_habitat_possible$result.threats, pattern="destructive fishing|destructive fisheries")] <- 1
trawl_habitat_possible$destructive[grepl(trawl_habitat_possible$result.usetrade, pattern="destructive fishing|destructive fisheries")] <- 1
sum(trawl_habitat_possible$destructive,na.rm=TRUE)

write_csv(trawl_habitat_possible, file.path(dir_data, "trawl_habitat_output.csv"))
#Looked into one of these species and it just happened these are both threats. No causation. 
```



```{r output-data-tidy}

text_threats <- read.csv(file.path(dir_data, "narrative_threats_output.csv")) %>% 
  rename(iucn_sid=iucn_id)
text_threats$trawlers <- ifelse(text_threats$bottom_trawl==1|text_threats$pelagic_trawl==1|text_threats$trawl_unspec==1, 1, NA)
text_threats <- text_threats %>% 
  gather(key="super_code", value="threat", -iucn_sid) %>% 
  filter(is.nan(threat)==F) %>% 
  filter(is.na(threat)==F) %>% 
  mutate(super_code = gsub(super_code, pattern="_", replacement=" "))
text_threats <- text_threats %>% left_join(all_species %>% dplyr::select(result.taxonid, result.scientific_name), by=c("iucn_sid"="result.taxonid")) %>% 
  rename(scientific_name = result.scientific_name) %>% 
  mutate(scientific_name = as.character(scientific_name))

text_threat_list <- text_threats %>% pull(scientific_name) %>% na.omit() %>% unique()

for (species in text_threat_list){
  new_sids <- all_species %>% filter(result.scientific_name==species) %>% pull(result.taxonid)
  
  if(length(new_sids) > 1){
    gears <- text_threats %>% filter(scientific_name==species) %>% pull(super_code)
    new_text_threats <- as.data.frame(expand.grid(iucn_sid= new_sids, 
                                  super_code = gears,
                                  threat=1,
                                  scientific_name=species))
    text_threats <- bind_rows(text_threats, new_text_threats)
  }
 
}
text_threats <- text_threats %>% distinct()
write_csv(text_threats, file.path(dir_data, "narrative_threats_output_tidy.csv"))

```

